### ISSUE TITLE
Date shift

### ISSUE THREAD

**Issue by ed-ortizm** [CLEOsat-group/satellite-tracking#4]
Solution:

- Recycled datetime objects, rather than creating a new one in each loop in the visibility computation

@JTregloanReed  report:
"""
I found a bug today when I tried to run the code for this evening 2021 08 31. The bug caused the code to crash as there are only 31 days in August. I found the issue as when the time passes midnight, we add 1 day, which makes August 32. So I added a couple of lines to test this and if this happens to reset day to 1 and month += 1.

This works for today but as there are different days per month and only 12 months per year we need to add an additional set of if statements to take this into account.
"""
Error from the termimal
"""
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "track.py", line 89, in <module>
    results = pool.map(compute_visible_parallel, satellites_list)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: day is out of range for monthinal:
"""

**Comment by ed-ortizm** [comment]
corrected using timedelta object from datetime module. now timedelta is in seconds and is set in the .ini file to 60 seconds
